### PR TITLE
Changed Websocket to support threads on more platforms.

### PR DESCRIPTION
**Pull request by JadeWhite**
In Websocket.cs, the preprocessor flags read:
```
#if !UNITY_EDITOR && (UNITY_WEBGL || !UNITY_WEBPLAYER)
private bool SupportsThreads { get { return false; } }
 #else
private bool SupportsThreads { get { return true; } }
 #endif
```
this makes it so SupportsThreads = false for all platforms except for the WebPlayer and Editor.

Due to this, when my master server was down, ConnectionToMaster.cs's call to Connect() froze the main thread in my iOS game. This was because SupportsThreads was set to false, making it use the non-threaded m_Socket.Connect() on line 146. The freeze lasted 85 seconds, which is roughly the amount of time for the default 90 second Websocket timeout. Interestingly, this freeze appears to not occur on OSX/Windows Standalone Builds, presumably despite using the non-threaded version.

On my fork, I changed the flags to 
`#if !UNITY_EDITOR && (UNITY_WEBGL)`
to enable threading on all platforms except for WebGL. According to https://forum.unity.com/threads/webplayer-multi-threading.76087/ , threading is supported on the webplayer.

Then I changed Connect() to ConnectAsync(), but the old approach probably works just as well.

I left .Send() and .Close() instead of changing them to their async varieties.  Other pieces of code appear to require them to be invoked in order/immediately.

I've tested my changes on iOS and the Editor, and it appears to be working, but tests on more platforms would be nice.   Do these changes look okay?

### CODE REVIEW

**Comment by JadeWhite** [comment]
Also tested it on Mac and Windows standalone too.

**Comment by JadeWhite** [comment]
Replacing Close() with CloseAsync(), allows the game to exit swiftly.

In the Editor however, a quick restart the game locks it up again, presumably waiting for the CloseAsync() to timeout. This thankfully probably won't happen often in game builds, because CloseAsync() is only called in OnApplicationQuit(), or if re-connecting to the master server.

A hacky solution might be to set the timeout to be closer to ~4 seconds. Just for the sake of the editor. However, m_Socket.WaitTime does not affect the hardcoded timeout.          

By using the changes in this pull request for Websocket Sharp, 
https://github.com/sta/websocket-sharp/pull/293
it would be possible to set the timeout using m_Socket.TcpTimeout = TimeSpan.FromSeconds(4); 

I would probably give this a shot later.

**Comment by JadeWhite** [comment]
Turns out the restart freeze was coming from calling ConnectAsync(), not CloseAsync().
Despite my best efforts integrating sta/websocket-sharp#293 and replacing every timeout with TcpTimeout - I couldn't seem to get rid of the freeze with ConnectAsync(). So I reverted the change.

The benefit of this pull request still stands though, it should still eliminate the Connect() freeze when the master server is down. Tests on more platforms should be done before it's considered final.

**Comment by JoaoBorks** [comment]
On which platforms have you tested already? We could help testing if you want

**Comment by JadeWhite** [comment]
Ah, my bad. I’ve only tested these recent changes in the OSX Editor. 

Ideally, I’d test it on a Windows/OSX stand-alone, and then iOS or Android using il2cpp - in case that would mess with the threading. If those two work, I assume other platforms should be fine.

Could probably give iOS and OSX standalone a shot later today.

**Comment by JadeWhite** [comment]
Yikes, the tests didn't work. Turns out I was still using my version of WebsocketSharp when I observed that it was working, and reverting to the original made the problems visible again. 

With WebsocketSharp unmodified:
OSX Standalone: Freezes at .Close() for ~90 seconds.
OSX Editor Immediate Restart:  Freezes at .Connect() for ~90 seconds.

With modifications to WebsocketSharp:
OSX Standalone: No visible freezes. (interestingly)
OSX Editor Immediate Restart: Freezes at Connect() for 4 seconds.
iOS il2cpp: No visible freezes.

To modify Websocket Sharp, I pulled sta/websocket-sharp#293 and added the following to tcpClientWithTimeout().
```
TcpClient client = new TcpClient ();
client.GetStream().WriteTimeout = WaitTime.Milliseconds;
```
All other timeouts can stay as they were. I've published my fork of Websocket Sharp with these changes here:
https://github.com/JadeWhite/websocket-sharp.git
I've also included the new websocket-sharp.dll in the commit.

As mentioned before, I've tested these changes on OSX Standalone, iOS and the Editor. If someone could confirm this works on a Windows standalone, it feel it should be ready for a merge.

**Comment by JoaoBorks** [comment]
How are we here? Do the `Connect()` freeze is still a thing?

**Comment by JadeWhite** [comment]
Yeah unfortunately, I wasn't able to find a solution. 

When restarting a project in the Editor with the master server down, m_Socket.Connect() freezes for ~90 seconds. At least with the preprocessor changes, it doesn't seem to occur in builds, or when using the debugger.

If I recall, I ended off being confused with
`ThreadPool.QueueUserWorkItem((status) =>
{
      m_Socket.Connect();
});`
for some reason Connect() freezes the entire game despite being run in a different thread.

**Comment by shubhank008** [comment]
How about adding a server online/accessibility check before the Connect() to try a failsafe detection to first make sure the server is online (perhaps ping IP ?) and if that port is accessible (TCPClient ?).  
If true, then allow the method to proceed, otherwise just return and show a error or try reconnect after a while ?  

I was thinking to create a BOOL method checkIfServerAccessible() with the following:    

```
TcpClient tcpClient = new TcpClient();

     try 
     {
       tcpClient.Connect("mastersrv.game.com", 5000);
       return true;
     } 
     catch (Exception)
     {
       return false;
     }
```

**Comment by JadeWhite** [comment]
...That actually might be a good hack ... Though probably not TcpClient, because if I recall that same Connect() method is what Websocket-sharp ends up calling under the hood.

You could even use Unity's Ping class with a timeout to avoid calling Connect().  I'm going to give it a shot sometime over the weekend.

**Comment by JadeWhite** [comment]
Sick! It looks like that works.

I added the following to Connect()
`Ping ping = new Ping(mUrl.Host);
	            
	            //The ping send/receive takes about a second, so we wait for it to complete.
	            while (!ping.isDone)
	            {
		            yield return null;
	            }
	            
	            //If the ping succeeded, the time will be 0 or higher, otherwise -1. 
	            if (ping.time >= 0)
	            {   
		            runThread(() =>
		            {
			            m_Socket.Connect();
		            });
	            }
	            else
	            {
		            m_Error = "Barebones Websocket: Could not contact \"" + mUrl.Host + "\" with Ping.";
	            }`

I've tested it connecting locally and to my remote server, everything seems to work great.

There are two catches though:
1. If your remote machine is running but your MasterServer process isn't, you'll still get the 90 second freeze. 
2. If you're making a Windows Store App, you need to make sure the server's port 80 is open, and InternetClient capability is enabled in Package.appxmanifest. This is because UWP doesn't have a ping library right now. https://docs.unity3d.com/ScriptReference/Ping.html

**Comment by shubhank008** [comment]
@JadeWhite 

> If your remote machine is running but your MasterServer process isn't, you'll still get the 90 second freeze.  

That is actually the most important part and was my main concern actually. In my case, I encountered this problem by chance when I was restarting my server/master server was down.  
So in real world there will be cases where your actual server is up but your Master Server is not (which I think is the actual scenario since the server being up or not doesnt really matter if MS isnt running on it), so I really think we ought to find a failsafe to prevent this hanging by checking for master server rather than just the actual server.  
This is specially true in cases where your MS can crash or hang due to heavy load even though the main server's IP would still ping.  

That was also why I in my suggested "hack" I was more keen on the checking port part which master server uses rather than just the IP (which the actual server uses).  
But as you mentioned, if TCPConnect cannot be used to check if port is open and accessible, we gotta find some other way to do this.  

Currently I can think of a few "theoretical" ways to do this:  

1. Check the master server ip and port for accessibility, chances are if the port is available then master server is running.  
Can we perhaps make use of this instead of TCPClient ? https://docs.unity3d.com/ScriptReference/Network.TestConnection.html    
2. Put the Connect() or connection part in a separate thread so that it doesnt Jam the main thread ? Async connection is what I mean.  
3. When the Connect fails for the first time jamming the screen, do not auto retry and instead create a callback where perhaps we can show a error to user that there is a problem with connection to master server and show a Manual Button to retry the connection.  
This is specially good for cases where its user's own firewall or ISP blocking connection to master server (even though MS is online). Though I think this should be the last resort as to just make sure it doesnt keep jamming the game client.  

4. Last but not the least, I am not sure if this will apply to everyone but this is what I am personally thinking of doing.  
Instead of having Game Client try to detect master client being online, I am thinking to do vice verse using a HTTP API (or just a weburl with JSON output like website.com/master.json) where the master server reports if its online or not.  
How this will work is that master server (via its own code/client or via the parent server) will periodically check if its still alive (not hanged/crashed) and that its IP:PORT is accessible by outside. 
If it is, it will then report the same to the HTTP API/WEB using a PUSH.  
On the client side, instead of detecting master server, client can instead directly check on the WEB API via HTTP GET if the JSON is true or false (master online or not). If it is online, then proceed with connection.  
This also has the added benefit of pseudo-detecting problems with user's firewall/ISP as if user is still not able to connect despite master being online (reported by API), then that means its user's own network blocking the connection.  


As I said, 4th might not apply for everyone but I personally think thats the route I am going for, specially since I am using hostnames anyways for my servers (master.loved.gamerzdan.com) so I will just setup the API check there (master.loved.gamerzdan.com/master.php).  

I think the API can be just a simple universal php code like :  

```
<?php  

$masterOnline = false;  

if($_POST["result"]){
//Write the result of POST request into some text file like ./result.txt as simple true or false
}
if(file_exists("./result.txt")){
//Read latest result from updated result file, other wise masterserver reports offline
$masterOnline = $result;
}

$data = array("result" => $masterOnline);

header('Content-Type: application/json');
echo json_encode($data);

?>
```

**Comment by JadeWhite** [comment]
Ah, my apologies - I suppose my ping code was more of the real "hack" :P

1. That looks promising, but it might require the old Unity Master Server process. It says it requires a server instance, but it also says it only uses connecting to it as a success value (so it might work fine with a generic socket)... Would have to test it to be sure.

 2. Unfortunately this is what I'm caught up on,
As it is, ThreadPool.QueueUserWorkItem((status) => { m_Socket.Connect(); }); places Connect() on a new thread. It logically shouldn't block the main thread, but for some reason it does on restart...

If I were to guess at more potential solutions...
 - I might try creating a Socket directly in a thread (not referenced anywhere outside), and see if that locks stuff up on restart. I'm thinking if it doesn't lock up, there's a old memory access lock issue of some sort (I really have no idea). If it does lock up, it might indicate the problem is deeper into the process of how Unity handles the editor play mode.
- TcpClient.ConnectAsync() is a new async connect method in UWP. But it unfortunately won't work for platforms other than Windows Store Apps right now (that is, if it does work). 
- The Connect() threads seem to continue after play mode is stopped, so we could try some method of ensuring they're killed immediately.... actually I want to test this.... (Update) No luck... 
- I found a thread with people with the same problem https://forum.unity.com/threads/system-thread-abort-not-working.34095/ Apparently a solution is to call abort() on all the threads. However, because that doesn't stop them, Create a "dummy socket" on the same thread, then send some data to wake it up and cause the thread to exit. I'm not quite sure how set that up though.

3. Ever since the preprocessor changes, I've only observed the 90 second freeze happening in the Editor. I haven't been able to observe it yet in my test builds. From your description, have you been experiencing it in builds? 

4. I'm not too familiar with php - but if people could integrate this into their projects without too much manual setup It would serve as a good workaround at this point.... If it works for you and does the job, godspeed :)

**Comment by diegoarx** [comment]
Thanks, this saved me. My problem was very similar i couldnt connect to masterserver from servers in the same internal network, i was using a google Ubuntu server that didnt work with threading, so i set threading to false in Websocket.cs and it worked. My doubt is if it is the Ubuntu 16.04 LTS that didnt support it or the cpu

**Comment by MostHated** [comment]
Depends on what you are paying for with your host, there very well might not be any threading, as every cpu core, thread, clock cycle, you have to pay for typically. I have not looked into googles hosting much, but if its anything like Amazon, you very very specifically get what you pay for / pay for what you use. I like DigitalOcean as my host, as I just pay a flat rate and don't have to worry about much. Ubuntu definitely is capable of it, just depends on what your host has enabled for you to use.

**Pull request merged**
